# raibid-cli Minimal Configuration
# =================================
# This is a minimal configuration file with only essential settings.

cluster:
  name: "dgx-spark-ci"
  namespace: "raibid-ci"

api:
  host: "localhost"
  port: 8080

agents:
  min_count: 0
  max_count: 8

gitea:
  url: "http://gitea.raibid-ci.svc.cluster.local:3000"
  admin_user: "admin"

redis:
  url: "redis://redis.raibid-ci.svc.cluster.local:6379"
  stream_name: "ci-jobs"
  consumer_group: "ci-workers"
