# Code Coverage Configuration

[report]
out = ["Html", "Xml"]
output-dir = "coverage"

[run]
timeout = 300
test-threads = 1

[coverage]
exclude-files = ["*/tests/*", "*/examples/*"]

[instrumentation]
engine = "Llvm"
workspace = true
