---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/component: autoscaler
    app.kubernetes.io/part-of: raibid-ci
    app.kubernetes.io/managed-by: raibid-cli
