---
# Kustomization for KEDA resources in raibid-ci namespace
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: raibid-ci

resources:
  # Authentication for Redis
  - triggerauth.yaml

  # ScaledJob for CI agents
  - scaledjob.yaml

# Common labels
commonLabels:
  app.kubernetes.io/part-of: raibid-ci
  app.kubernetes.io/managed-by: kustomize

