---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: raibid-ci-agent-scaler
  namespace: raibid-ci
  labels:
    app.kubernetes.io/name: raibid-ci-agent
    app.kubernetes.io/component: ci-agent
    app.kubernetes.io/part-of: raibid-ci
    app.kubernetes.io/managed-by: keda
spec:
  # Target deployment to scale
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: raibid-ci-agent

  # Scaling limits
  minReplicaCount: 0  # Scale to zero when queue is empty
  maxReplicaCount: 10  # Maximum 10 concurrent agents

  # Polling interval (how often to check queue)
  pollingInterval: 10  # seconds

  # Cooldown period before scaling down
  cooldownPeriod: 300  # 5 minutes

  # Advanced scaling options
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 50
            periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
          - type: Pods
            value: 4
            periodSeconds: 15
          selectPolicy: Max

  # Triggers
  triggers:
  - type: redis-streams
    metadata:
      # Redis connection
      addressFromEnv: REDIS_ADDRESS
      stream: raibid:jobs
      consumerGroup: raibid-workers

      # Scaling thresholds
      pendingEntriesCount: "1"  # Scale up when 1+ pending jobs
      lagCount: "5"  # Additional scaling based on lag

    # Authentication
    authenticationRef:
      name: raibid-redis-trigger-auth
