---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
  labels:
    app.kubernetes.io/name: flux
    app.kubernetes.io/component: gitops
    app.kubernetes.io/part-of: raibid-ci
    app.kubernetes.io/managed-by: flux
