---
apiVersion: v1
kind: Namespace
metadata:
  name: raibid-gitea
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/component: git-server
    app.kubernetes.io/part-of: raibid-ci
    app.kubernetes.io/managed-by: raibid-cli
