# Gitea Helm Chart Values
# Production configuration for raibid-ci

## Gitea image configuration
image:
  repository: gitea/gitea
  tag: "1.21.0"
  pullPolicy: IfNotPresent

## Pod replicas (single replica for MVP)
replicaCount: 1

## Strategy
strategy:
  type: Recreate

## Service configuration
service:
  http:
    type: NodePort
    port: 3000
    nodePort: 30080
  ssh:
    type: NodePort
    port: 22
    nodePort: 30022

## Ingress (disabled for MVP, using NodePort)
ingress:
  enabled: false

## Persistence
persistence:
  enabled: true
  size: 10Gi
  storageClass: "local-path"
  accessModes:
    - ReadWriteOnce

## PostgreSQL database
postgresql:
  enabled: true
  persistence:
    size: 5Gi
    storageClass: "local-path"
  auth:
    username: gitea
    password: gitea  # Change in production
    database: gitea

## Redis cache
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

## Gitea configuration
gitea:
  admin:
    username: raibid-admin
    # Password will be generated by raibid-cli
    email: admin@raibid.local

  config:
    APP_NAME: "Raibid CI Git Server"
    RUN_MODE: prod

    server:
      DOMAIN: localhost
      ROOT_URL: http://localhost:30080/
      HTTP_PORT: 3000
      PROTOCOL: http
      SSH_PORT: 22
      SSH_LISTEN_PORT: 22
      DISABLE_SSH: false
      START_SSH_SERVER: true
      LFS_START_SERVER: true

    database:
      DB_TYPE: postgres
      HOST: gitea-postgresql:5432
      NAME: gitea
      USER: gitea
      PASSWD: gitea  # Change in production

    cache:
      ADAPTER: redis
      HOST: redis://gitea-redis-master:6379/0

    session:
      PROVIDER: memory

    webhook:
      ALLOWED_HOST_LIST: "*"
      SKIP_TLS_VERIFY: true

    actions:
      ENABLED: true

    packages:
      ENABLED: true

    # OCI Container Registry
    packages.container:
      ENABLED: true

## Resource limits
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi

## Security context
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

## Probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 200
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 10

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

## Labels
commonLabels:
  app.kubernetes.io/name: gitea
  app.kubernetes.io/component: git-server
  app.kubernetes.io/part-of: raibid-ci
  app.kubernetes.io/managed-by: helm
