---
# Namespace for CI agents and build jobs
apiVersion: v1
kind: Namespace
metadata:
  name: raibid-ci
  labels:
    app.kubernetes.io/name: raibid-ci
    app.kubernetes.io/component: ci-namespace
    app.kubernetes.io/part-of: raibid-ci
    app.kubernetes.io/managed-by: raibid-cli

---
# Namespace for infrastructure services (Gitea, Redis, etc.)
apiVersion: v1
kind: Namespace
metadata:
  name: raibid-infrastructure
  labels:
    app.kubernetes.io/name: infrastructure
    app.kubernetes.io/component: infrastructure-namespace
    app.kubernetes.io/part-of: raibid-ci
    app.kubernetes.io/managed-by: raibid-cli

---
# Namespace for monitoring and observability
apiVersion: v1
kind: Namespace
metadata:
  name: raibid-monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: monitoring-namespace
    app.kubernetes.io/part-of: raibid-ci
    app.kubernetes.io/managed-by: raibid-cli
