---
# Local Path Storage Class
# k3s comes with local-path-provisioner by default
# This manifest ensures it's configured correctly

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    app.kubernetes.io/name: local-path
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: raibid-ci
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true

---
# Local Path Provisioner ConfigMap
# Customize storage paths for DGX Spark

apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: kube-system
  labels:
    app.kubernetes.io/name: local-path-provisioner
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: raibid-ci
data:
  config.json: |-
    {
      "nodePathMap": [
        {
          "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths": ["/var/lib/rancher/k3s/storage"]
        }
      ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoSchedule
      containers:
      - name: helper-pod
        image: busybox:1.36
        imagePullPolicy: IfNotPresent
