---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: raibid-redis
  namespace: raibid-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: job-queue
    app.kubernetes.io/part-of: raibid-ci
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: "18.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: raibid-redis
  valuesFrom:
    - kind: ConfigMap
      name: redis-values
      valuesKey: values.yaml
