---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: raibid-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: job-queue
    app.kubernetes.io/part-of: raibid-ci
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
