---
apiVersion: v1
kind: Namespace
metadata:
  name: raibid-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: job-queue
    app.kubernetes.io/part-of: raibid-ci
    app.kubernetes.io/managed-by: raibid-cli
