---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: raibid-redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
    - name: metrics
      port: 9121
      targetPort: metrics
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: raibid-redis
    app.kubernetes.io/component: master
