---
# GitRepository source for Flux to sync from
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: gitea-credentials
  url: http://gitea.raibid-gitea.svc.cluster.local:3000/raibid/infrastructure
---
# Kustomization for flux-system components
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infra/flux/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
