name: Documentation

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'

jobs:
  validate:
    name: Validate Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run documentation checks
        run: |
          chmod +x scripts/check-docs.sh
          ./scripts/check-docs.sh
